### ISSUE TITLE
Issue with Redmine 3.0.3

### ISSUE THREAD

**Issue by AmiDesai** [jijeshmohan/redmine_track_control#33]
Hello!

The plugin is great, perfectly fits my requirements... But now as i am upgrading to latest version of Redmine that is 3.0.3, this plugin has to be made compatible to 3.0.3 too.

Right now, it throws this error when View All Issue link is clicked. See below for the error obtained from log file.
-  NoMethodError (undefined method `enabled_modules' for nil:NilClass):
-  app/models/query.rb:242:in `build_from_params'
-  app/models/issue_query.rb:120:in `build_from_params'
-  app/helpers/queries_helper.rb:198:in `retrieve_query'
-  app/controllers/issues_controller.rb:46:in `index'

**Comment by fishermans** [comment]
+1 Same on 2.6.6

**Comment by jijeshmohan** [comment]
Created a new branch for remine 3.x . you can [download](https://github.com/jijeshmohan/redmine_track_control/archive/redmine3.zip) the plugin  and try ( make sure that the folder name is `redmine_track_control` under plugins directory ). 

@fishermans this should work with 2.6.6 as well( not tested )

**Comment by fishermans** [comment]
Thanks, I already fixed two issues yesterday. I'll check it in asap and send a pull request.

**Comment by alexspetty** [comment]
Testing this now.

**Comment by alexspetty** [comment]
This fix is working great on 3.0.1

**Comment by jijeshmohan** [comment]
thanks @iraycohen .

**Comment by fishermans** [comment]
Not working on 2.6.6. Same issue.

NoMethodError (undefined method `enabled_modules' for nil:NilClass):
   app/models/query.rb:235:in`build_from_params'
   app/models/issue_query.rb:119:in `build_from_params'
   app/helpers/queries_helper.rb:179:in`retrieve_query'
   app/controllers/issues_controller.rb:56:in `index'

Simply go to "Projects" main page and click on "Show all issues".
 http://<redmine url>/issues
